name: chat_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_storage: ^10.2.18
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  shared_preferences: ^2.0.15
  pinput: ^2.2.11
  rename: ^2.0.1
  video_player: ^2.4.7
  file_picker: ^5.0.1
  flutter_easyloading: ^3.0.5
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
